apiVersion: v1
kind: Service
metadata:
  name: {{ include "daywriter.fullname" . }}
  labels:
    {{- include "daywriter.labels" . | nindent 2 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: http
  selector:
    {{- include "daywriter.selectorLabels" . | nindent 4 }}
